# test this file with
#   goreleaser --skip-publish --rm-dist --config goreleaser.yml
builds:
  - main: ./cmd/wtimer
    binary: wtimer
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: binary
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
    files:
      - none*
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
